### ISSUE TITLE
Manuels Rechner vor Ort

### ISSUE THREAD

**Issue by jlee7** [jlee7/ggj2015#2]
Ey, hast du einen Rechner, den du zur GJ nehmen kannst? 
Oder kannste dir einen besorgen?

**Comment by perelin** [comment]
Desktop da aufbauen ist auch kein Problem. Da ist immer jemand der aufpasst.

**Comment by M-Kuenstler** [comment]
Rechner mitnehmen?...ungern!...
Können wir ne Whatsapp Gruppe aufmachen und dort weiterquatschen?

Mach mal Josef!!!

**Comment by jlee7** [comment]
Gruppe erstellt!

**Comment by perelin** [comment]
Könntest hier noch schnell einen einkaufen: http://www.ebay.de/itm/VTech-Lerncomputer-School-Laptop-E-bei-Sofortkauf-0Versandkosten-/331453181992 ;)

**Comment by M-Kuenstler** [comment]
Danke für den Tipp!!! Ich habe uns mal drei Stück bestellt.
Kann nichts mehr schief gehen!
