### ISSUE TITLE
Genre des Spiels

### ISSUE THREAD

**Issue by jlee7** [jlee7/ggj2015#3]
Unabhängig von dem Thema des Spiels kam auf, dass die Festlegung auf ein Genre sinnvoll wäre. 

Beispiele:
Knobelspiel
Puzzle
Sidescroller Jump n Run
Musikspiel
Simples (Text-)Adventure 
...

**Comment by jlee7** [comment]
Ich finde n Minishooter a la Asteroids auch gut, aber knobeln auch.

**Comment by jlee7** [comment]
Ich habe gerade bei einem Kollegen folgendes Design gesehen:

Ein Webgame, das ein Brettspiel ist und versucht so wie ein echtes Brettspiel auszusehen. 
Dachte als Gedankenfutter ist es was. 

![card hunter](https://cloud.githubusercontent.com/assets/9515990/5815713/594a6ea6-a098-11e4-9cdd-b394cc118dd6.png)

**Comment by perelin** [comment]
Ich bin ja für: So-einfach-wie-möglich ;)

Musikspiel (komplizierte Timing-Dinge) und Adventure (zu viel Kontent) sind da quasi schon raus. 
Simples Brettspiel könnte man sich überlegen.
Jump´n Run ist von der Komplexität auch am oberen Limit.
Spaeshooter ist machbar, aber auch ein wenig langweilig ;)

**Comment by jlee7** [comment]
Sollen wir vielleicht nach Komponenten gehen, die wir "können"? 

Josef "kann":
- Random Objekte erzeugen und random bewegen lassen
- Steuerbares Spielerobjekt
- Schussfunktion des Spieleobjektes
- Memory (Karsten aufdecken und matchen)
- Schnick Schnack Schnuck

**Comment by perelin** [comment]
Is ja quasi schon fast alles ;)

Am Dienstag, 20. Januar 2015 schrieb jlee7 :

> Sollen wir vielleicht nach Komponenten gehen, die wir "können"?
> 
> Josef "kann":
> - Random Objekte erzeugen und random bewegen lassen
> - Steuerbares Spielerobjekt
> - Schussfunktion des Spieleobjektes
> - Memory (Karsten aufdecken und matchen)
> - Schnick Schnack Schnuck
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jlee7/ggj2015/issues/3#issuecomment-70656012.

## 

---

Sebastian Patiño-Lang, B.Sc.

|  Rheinstraße 43  |  76185 Karlsruhe  |
|   +49 172 894 13 17   |  patino@p2lab.de  |

**Comment by jlee7** [comment]
So-einfach-wie-möglich braucht dennoch ein Genre. ^^
Ich glaube das ist vorrangig wichtig, weil wir uns ja nicht die volle Doku reinziehen können, sondern gücken müssen was wir wirklich brauchen. 

Vom Stil her wäre ich für so kubisches Zeug. Relativ einfach zu erstellen und das ist ja momentan auch voll im Trend. ^^

**Comment by perelin** [comment]
Bin da für alles offen. Denke wir sollten alles vermeiden, was viele Assetts benötigt (große Level, viel Text/Bilder, etc). Irgendwas mit einem Screen auf dem dann Dinge ein wenig Random passieren und der Spieler damit umgehen muss. Maximal noch PvP am Ende, nix übers Netzwerk.

**Comment by perelin** [comment]
Um es abzukürzen: sowas wie ein SpaceShooter/TopDownShooter wäre für mich total ok.

**Comment by jlee7** [comment]
Für mich auch. Hauptsache E-Gitarrensounds.

**Comment by perelin** [comment]
Geil.

**Comment by M-Kuenstler** [comment]
Bin definitiv auf für "so einfach wie möglich".
Den Vorschlag, das wir nur einen Screen haben, auf dem Sich alles abspielt,  finde ich gut und sehr zweckmäßig, da sonst tatsächlich die Assets zu viel werden können!

E- Gitarren-Sound ist ein MUSS!! ;)

Vom Genre her mag ich Puzzle / Knobelspiel ... hätte aber auch gerne ein Charakter mit einer kleinen Animation in unserem Spiel.... Sowas zum Beispiel: http://www.kongregate.com/games/glimajr/continuity 

Ich freue mich echt aufs Wochenende :dancer:

**Comment by jlee7** [comment]
Das Spiel ist ja total witzig!!

**Comment by perelin** [comment]
Sehr cool! Aber schon eindeutig komplexer als was wir vorhaben soltlen ;) Animation ist nice, würde ich aber auch als Sahnehäubchen sehen, wenn am Ende noch Zeit ist.

**Comment by jlee7** [comment]
Ja. Ich denke auch.
Sollen wir mal so grob staffeln?
1. Skizze des Spiels
2. Funktionierende Komponenten produzieren
3. Funktionierendes (Zusammen-)Spiel
4. Einbauen der nice-to-haves

Oder wat?

**Comment by perelin** [comment]
1
2 und 3 in Iteration, quasi alle paar Stunden mal zusammenschrauben und schauen wie es ist
4

**Comment by M-Kuenstler** [comment]
Ihr habt Recht: Erstmal keine Animation...denke der Rest wird uns schon genug beschäftigen ^^

Was haltet Ihr von der Idee: 
**Schere Stein Papier auf einer Art Schachbrett**
- Man spielt es zu zweit und jeder darf abwechseln ziehen (rundenbasiert)
- Eine Team besteht aus 5 Figuren Schere, 5 Figuren Steine, 5 Figuren Papier
- Jeder Figur kann nur eine bestimmte Anzahl an Zügen pro Runde
- Sobald sich zwei Figuren aus unterschiedlichen Teams begegnen, kommt das bekannte "Schere-Stein-Papier"- Prinzip zum Einsatz und eine Figur wird vom Spielbrett genommen
- berührt eine Figur sogar zwei oder mehrer gegnerische Figuren kann er auch mehrere Figuren gleichzeitig vom Spielbrett befördern
- Gewonnen hat, wer zuerst seinen Gegner besiegt

**Comment by perelin** [comment]
Sounds Nice! evtl mal dann auf Papier prototypen?

**Comment by jlee7** [comment]
Wieso hab ich son Grinsen beim Lesen im Gesicht? ^^

**Comment by M-Kuenstler** [comment]
@jlee7 : Weiß nicht was Du meinst?  Für dein Gesicht bin ich nicht verantwortlich! :trollface:

**Comment by jlee7** [comment]
Wir haben gestern zwei Varianten von dem Spiel ausprobiert und war weniger erfolgverpsrechend. Plan umgeworfen und offen für neues.

**Comment by jlee7** [comment]
PARTY HARD!
