### ISSUE TITLE
Team-Name

### ISSUE THREAD

**Issue by perelin** [jlee7/ggj2015#4]
Wie nennen wir uns?

**Comment by jlee7** [comment]
SMJ - Super Mega Josef
MJS - Mega Josef Super
JSM - Josef Super Mega
SJM - Super Josef Mega
MSJ - Mega Super Josef
JMS - Josef Mega Super

Sucht euch einfach eins aus!

**Comment by jlee7** [comment]
Mit Null:
From Hero to Zero
The Mask of Zero
Zero Quest
Zero and a half men
Half zero, half amazing
Zerocopter
Zero squared
The one and only - Zero!
Nothing but zero
Zerosaurus
...

**Comment by jlee7** [comment]
Mit Eins:
One two tree
The one and not only
Three Ones (3x1s)
We One You!
One Tan Soup
I One!
One der Woman

**Comment by jlee7** [comment]
Ok, ich muss mal arbeiten.

**Comment by perelin** [comment]
Warum 0 und 1?

**Comment by perelin** [comment]
Zerosaurus oder Zerocopter

**Comment by jlee7** [comment]
Mit Drei:
DreiRad
DreiRäder
Better Drei than Wet
mpDrei
Die zwei gloreichen 3
3Pod
Growing on a Three
Threedom
Tripe Double Single
Many Threes make a Forest
The bees see three trees
Season 3

**Comment by perelin** [comment]
Warum 0-1-3?

**Comment by jlee7** [comment]
Random:
Sebastian and Boys
Manuel and Boys
Josef and Boys
A Boy and Boys
Bolce Boyce
Boyoncé
Heavy...not!
BlaFoo Productions
Minimalists
Maximalists
Merlin is dead!
....

**Comment by jlee7** [comment]
FraKaBo

**Comment by perelin** [comment]
Was rauchst Du eigentlich Alter? ... bring was davon mit!

**Comment by jlee7** [comment]
It has always been inside my head...
Most of it comes, when I'm in bed...
Keep the eyes closed until you see...
Many words - made of ABC!

**Comment by perelin** [comment]
Dein Gesicht ist made of ABC!

**Comment by M-Kuenstler** [comment]
Mein Favorite bisher: The bees see three trees
haha...!!!! Direkt auch ein Logo im Kopf!

**Comment by M-Kuenstler** [comment]
Face/Gesicht:
Facepalm
In your face
Face-tte
Schwergesichter
Übergesichter
Gesichter aus der Gruft

(Man... das macht voll Spaß :smile: )

**Comment by M-Kuenstler** [comment]
So...jetzt aber mal produktiv:
Meine Top3 (in absteigender Reihenfolge):
- The bees see three trees
- Zero Quest
- Heavy...not!

Und Eure?

**Comment by perelin** [comment]
TBSTT! 

wartet... ist das jetzt Team- oder Spielname?

**Comment by jlee7** [comment]
Teamname!

**Comment by jlee7** [comment]
FAIL
