### ISSUE TITLE
Neue Ordner angelegt

### ISSUE THREAD

**Issue by jlee7** [jlee7/ggj2015#5]
Wir können ja schon einmal Zeug sammeln.
Snippets, Grafiken und Sounds.
@M-Kuenstler : Vielleicht hast du ja irgendwelche Riffs schon, die vorerst als Hintergrundmusik oder so herhalten können. Grafiken kannste auch einfach reinhauen. Ich bin dafür, dass wir auch unsere Blenderobjekte da rein tun. 

@perelin : In "useful" hab ich uns mal ein cheat sheet reingelegt. ^^ Ich denke das können wir sehr gut gebrauche.

**Comment by perelin** [comment]
Geilomat!

**Comment by perelin** [comment]
Evtl die URL für die Cheatsheets auch ins Wiki?
