### ISSUE TITLE
Architektur

### ISSUE THREAD

**Issue by perelin** [jlee7/ggj2015#6]
Damit @jlee7 und @perelin gescheit zusammen am Code arbeiten können sollten wir das Spiel nach dem MVC Pattern aufbauen. Hier eine gutes Tutorial (auch im Wiki verlinkt): http://ezide.com/games/writing-games.html

**Comment by jlee7** [comment]
Nice!

**Comment by jlee7** [comment]
Da ja das Endergebnis ungefähr stehen muss, um das umzusetzen, sollten wir mit dem GENRE weiter machen. ^^

**Comment by perelin** [comment]
Nee, das ist unabhängig vom Genre. Egal was wir für ein Spiel machen, es wird einen Views, Controller und Models haben.

**Comment by jlee7** [comment]
Hmm, okay. Ich lese das mal. Morgen.

**Comment by jlee7** [comment]
SEHR INTERESSANT BISHER!!

**Comment by jlee7** [comment]
@perelin 
Machen wir dann beispielsweise für den Eventmanager ne eigene Datei oder wie läuft das dann?
Dann müssen wir auch Schnittstellen zwischen den Teilen definieren, ne?
In welcher Form was übergeben wird und so. Nice. Das war eines der Sachen, die ich lernen wollte.

**Comment by perelin** [comment]
Jup, genau so. Würde alle Komponenten in eigene Dateien packen und nur noch über Schnittstellen zusammenschrauben. So können wir bequem getrennt an Zeug arbeiten.

**Comment by jlee7** [comment]
Stark!
