### ISSUE TITLE
Video Dokumentation

### ISSUE THREAD

**Issue by jlee7** [jlee7/ggj2015#7]
Hey Jungs,

ich fänd es ja super lustig, wenn wir unsere erste GameJam dokumentieren.
So, dass wir später eine echt coole Erinnerung daran haben. :+1:  

Vielleicht hat ja jemand von unseren Leuten Bock da mal vorbei zu schauen. Und uns nebenbei auch etwas zu essen zu bringen. :hamburger:

**Comment by perelin** [comment]
Ich habe Doku letztes Jahr mal so gemacht: https://www.youtube.com/watch?v=dpe3JysGyjA 
;)

**Comment by M-Kuenstler** [comment]
Sehr geil, Sebastian ^^
Wie hast Du das gemacht?

**Comment by perelin** [comment]
Das war auf nem Mac mit einem Script, dass alle paar Minuten ein Bild von der Webcam aufnimmt und dann zu einem Film zusammen klebt. Für Windows gibts da auch Programme.

https://code.google.com/p/chronolapse/ zB

**Comment by jlee7** [comment]
Machen wir! Mindestens das.

**Comment by jlee7** [comment]
Habe mal meine Action-Cam eingepackt. Leider hab ich meinen Gorilla-Pod heute morgen nicht mehr gefunden... ^^

**Comment by jlee7** [comment]
FAIL
