### ISSUE TITLE
Diversifiers

### ISSUE THREAD

**Issue by perelin** [jlee7/ggj2015#8]
Hier sind die Diversifiers für den GGJ2015:

http://globalgamejam.org/news/introducing-ggj-2015-diversifiers 

Damit kann man quasi "Extrapunkte" für sein Spiel bekommen (Gewinnen kann man aber nix ;)
- Noise Generator: The mechanic of the game is based on players having to stay in constant communication with each other.
- Folk: The game uses a folk or indigenous art style of your region.
- NES: Make the game playable on an old school console, either directly or through an emulator.
- Wrist Watcher: The game is playable on a smart-watch, or uses wearable technology in some way.
- Clueless Parents: The game helps kids teach something to their parents or other family members.
- Batch Job: The game is a batch file from any operating system, using command line tools found in an out of the box installation.
- Chimera: The game is played partly as a digital and partly as a non-digital (board, card, etc.) game.
- Hyper-Local: The game is set in your town/city and contains elements locals can identify, while still being entertaining for a global audience.
- Can I Try?: Any spectator of the game automatically becomes a player as well.
- This is How it Feels: The game raises awareness of how hate speech or unfair accusations feel, and what kind of effect they have on their targets.
- Stephen Hawking Can Play This: In the game everything (including any menus) can be navigated with one button, without any need for quick / precisely timed presses.
- Eagle Ear: The game is primarily visual, but is also playable by visually impaired  players, either through audio design, or through a screenreader (VoiceOver, Talkback, JAWS etc).
- Relatively Speaking: A game based on the 100th anniversary of Einstein’s theory of general relativity, which explained that massive objects cause a distortion in space-time, such as light bending around black holes.
- Public Domain Class of 2015: Make a game based on the works entered to Public Domain on 1st January 2015 - for instance works of Wassily Kandinsky, Edvard Munch, Edith Sitwell, Piet Mondrian, Antoine de Saint-Exupéry, Felix Nussbaum, Filippo Tommaso Emilio Marinetti, Glenn Miller, Flannery O’Connor, and Ian Fleming (cough, James Bond, cough), depending on your country.
- Code for Good (Sponsored by Intel): Make a game with the goal of improving literacy, or inspiring interest in science, technology, engineering and mathematics (STEM) fields.

**Comment by perelin** [comment]
Ich bin für "Stephen Hawking Can Play This" ;)

**Comment by jlee7** [comment]
HAHAHAHA
