### ISSUE TITLE
Final repository

### ISSUE THREAD

**Issue by jlee7** [jlee7/ggj2015#9]
Sollen wir das Repository so aufräumen, dass jeder Besucher direkt nur das Ergebnis der GameJam sieht?

**Comment by perelin** [comment]
lets do it! Josef, kannst du gerade mal ... ;)

**Comment by jlee7** [comment]
Ja, mach ich.

**Comment by jlee7** [comment]
Hab ich gemacht.

**Comment by jlee7** [comment]
Hm... glaube ich hab was falsch gemacht?
